services:
  frontend:
    build: ./bonsai-frontend
    container_name: react_frontend
    ports:
      - "3000:80" # Maps Nginx running in the frontend container to localhost:3000

  backend:
    build: ./Bonsai
    depends_on:
      - mysql
    container_name: spring_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/Bonsai
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=12tOronto10.

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 12tOronto10.
      MYSQL_DATABASE: Bonsai
    ports:
      - "3307:3306"

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
